### ISSUE TITLE
settings window bug 

### ISSUE THREAD

**Issue by k0ez13** [redsigma/Unofficial-Patch-for-MetroForSteam#54]
![image](https://user-images.githubusercontent.com/59665015/136109272-a783ca00-3e1c-436a-8b53-a5da96559a0c.png)
I no have idea how to fix this. (i use kde plasma)

**Comment by lyssieth** [comment]
I have the same issue, and also no clue how to fix it.

**Comment by redsigma** [comment]
From what i know this problem happens on manjaro linux. Try changing the font. 

For the solution is to revert back to default stream by renaming the metro skin folder. And you changed the settings you can rename the folder back and restart steam.

EDIT: Fixed in 291643daf3607c0059eaf0fa98c7b3f2377eef1f
