### ISSUE TITLE
Text is cut off in the key activation popup

### ISSUE THREAD

**Issue by GenesisFR** [redsigma/Unofficial-Patch-for-MetroForSteam#61]
After successfully activating a Steam key, we can see some text is cut off in the window, see the screenshot below.

![image](https://user-images.githubusercontent.com/3614449/165412183-b7109f68-f173-4d6f-8618-ddd85980bc57.png)

I think I'm using this revision https://github.com/redsigma/UPMetroSkin/commit/fdf68b6b0b58a1ee9a8ad3aa1666403b3f79f88f, haven't checked on the latest revision as it'd require me to activate another key :p.

**Comment by redsigma** [comment]
This is not a bug. It happens because of the fonts that metro uses. The fix would be to decrease the size of all fonts but this is too destructive, because it might require changes in other panels so there is no waste of space. There might also be problems with other languages. 

Not all panels wrap the text properly but this is a issue that valve needs to fix. Fortunately you dont see this window too often so it's not a big deal

**Comment by GenesisFR** [comment]
Makes sense, closing this then.
